### ISSUE TITLE
Remove password information in debug logs

### ISSUE THREAD

**Issue by rodcloutier** [devpi/devpi-ldap#21]
The password are present in clear text in the debug log (when starting the `devpi-server` with `--debug`).

Even if it is only for debugging, I think it should be removed and replaced with a clear way to enable printing the password if needed.

**Comment by fschulze** [comment]
Can you paste an example, without the actual password of course? I checked the source and don't see where the password would be logged in debug mode.

**Comment by rodcloutier** [comment]
Here you go. `<password>` are the actual two places where the password is in clear text.

```
2015-06-22 16:26:43,026 DEBUG NETWORK:socket wrapped with SSL using SSLContext for <ldaps://ldap-server - ssl - user: CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=NCSA,OU=my_company,DC=my_company,DC=org - unbound - closed - <local: 127.0.0.1 - remote: 10.129.1.10:636> - tls not started - not listening - SyncStrategy>
2015-06-22 16:26:43,026 DEBUG NETWORK:connection open for <ldaps://ldap-server - ssl - user: CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=NCSA,OU=my_company,DC=my_company,DC=org - unbound - open - <local: 127.0.0.1 - remote: 10.129.1.10:636> - tls not started - listening - SyncStrategy>
2015-06-22 16:26:43,026 DEBUG BASIC:refreshing server info for <ldaps://ldap-server - ssl - user: CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=NCSA,OU=my_company,DC=my_company,DC=org - unbound - open - <local: 127.0.0.1 - remote: 10.129.1.10:636> - tls not started - listening - SyncStrategy>
2015-06-22 16:26:43,026 DEBUG BASIC:start BIND operation via <ldaps://ldap-server - ssl - user: CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=NCSA,OU=my_company,DC=my_company,DC=org - unbound - open - <local: 127.0.0.1 - remote: 10.129.1.10:636> - tls not started - listening - SyncStrategy>
2015-06-22 16:26:43,026 DEBUG PROTOCOL:performing simple BIND for <ldaps://ldap-server - ssl - user: CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=NCSA,OU=my_company,DC=my_company,DC=org - unbound - open - <local: 127.0.0.1 - remote: 10.129.1.10:636> - tls not started - listening - SyncStrategy>
2015-06-22 16:26:43,028 DEBUG PROTOCOL:simple BIND request <{'authentication': {'simple': '<password>', 'sasl': None}, 'version': 3, 'name': 'CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=NCSA,OU=my_company,DC=my_company,DC=org'}> sent via <ldaps://ldap-server - ssl - user: CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=NCSA,OU=my_company,DC=my_company,DC=org - unbound - open - <local: 127.0.0.1 - remote: 10.129.1.10:636> - tls not started - listening - SyncStrategy>
2015-06-22 16:26:43,028 DEBUG PROTOCOL:new message id <3> generated
2015-06-22 16:26:43,028 DEBUG NETWORK:sending 1 ldap message for <ldaps://ldap-server - ssl - user: CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=NCSA,OU=my_company,DC=my_company,DC=org - unbound - open - <local: 127.0.0.1 - remote: 10.129.1.10:636> - tls not started - listening - SyncStrategy>
2015-06-22 16:26:43,029 DEBUG EXTENDED:ldap message sent via <ldaps://ldap-server - ssl - user: CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=NCSA,OU=my_company,DC=my_company,DC=org - unbound - open - <local: 127.0.0.1 - remote: 10.129.1.10:636> - tls not started - listening - SyncStrategy>:
>>LDAPMessage:
>> messageID=3
>> protocolOp=ProtocolOp:
>>  bindRequest=BindRequest:
>>   version=3
>>   name=CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=NCSA,OU=my_company,DC=my_company,DC=org
>>   authentication=AuthenticationChoice:
>>    simple=<password>
2015-06-22 16:26:43,030 DEBUG NETWORK:sent 98 bytes via <ldaps://ldap-server - ssl - user: CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=NCSA,OU=my_company,DC=my_company,DC=org - unbound - open - <local: 127.0.0.1 - remote: 10.129.1.10:636> - tls not started - listening - SyncStrategy>
2015-06-22 16:26:43,058 DEBUG NETWORK:received 22 bytes via <ldaps://ldap-server - ssl - user: CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=NCSA,OU=my_company,DC=my_company,DC=org - unbound - open - <local: 127.0.0.1 - remote: 10.129.1.10:636> - tls not started - listening - SyncStrategy>
2015-06-22 16:26:43,058 DEBUG NETWORK:received 1 ldap messages via <ldaps://ldap-server - ssl - user: CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=NCSA,OU=my_company,DC=my_company,DC=org - unbound - open - <local: 127.0.0.1 - remote: 10.129.1.10:636> - tls not started - listening - SyncStrategy>
```

**Comment by fschulze** [comment]
Hmm, that looks like it's coming from the library we use. Could be kinda tricky to disable from the plugin, since the logging is set up by devpi-server and currently plugins don't have an API to adjust logging configuration. We recently merged a PR which adds logging configuration: https://bitbucket.org/hpk42/devpi/pull-request/225/make-logging-configurable-via-an-external/diff
If that approach works, then we should document it.

**Comment by cannatag** [comment]
HI, I'm the author of the ldap3 library. The code in dev at https://github.com/cannatag/ldap3.git  should fix this issue. Can you try to use it? Let me know if you can't get the code from dev and rely on pypi for ldap3 installation. 

Bye,
Giovanni

**Comment by fschulze** [comment]
@cannatag Thanks for the information!

@rodcloutier did you have a chance to see if that fixes the issue? If so and when there is a new ldap3 release, I would make a new release with updated requirements.

**Comment by cannatag** [comment]
ldap3 0.9.8.6 has been released. It hides sensitive data in logging by default. Can you check it?

Thanks,
Giovanni

**Comment by rodcloutier** [comment]
@cannatag  Using ldap3 0.9.8.6 still show the password in debug logs

```
2015-07-09 09:39:16,575 DEBUG BASIC:instantiated <SyncStrategy>: <ldaps://ldap-server - ssl - user: CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=my_company,DC=my_company,DC=org - unbound - closed - <no socket> - tls not started - not listening - No strategy - async - real DSA - not pooled - cannot stream output>
2015-07-09 09:39:16,575 DEBUG BASIC:instantiated Connection: <Connection(server=Server(host='ldap-ncsa.my_company.org', port=636, use_ssl=True, tls=Tls(validate=0), get_info='NO_INFO'), user=u'CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=my_company,DC=my_company,DC=org', password=u'<password>', auto_bind='NONE', version=3, authentication='SIMPLE', client_strategy='SYNC', auto_referrals=True, check_names=True, read_only=True, lazy=False, raise_exceptions=False)>
2015-07-09 09:39:16,575 DEBUG NETWORK:opening connection for <ldaps://ldap-server - ssl - user: CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=my_company,DC=my_company,DC=org - unbound - closed - <no socket> - tls not started - not listening - SyncStrategy>
...
2015-07-09 09:39:16,589 DEBUG PROTOCOL:performing simple BIND for <ldaps://ldap-server - ssl - user: CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=my_company,DC=my_company,DC=org - unbound - open - <local: 10.128.32.247:57723 - remote: 10.129.1.242:636> - tls not started - listening - SyncStrategy>
2015-07-09 09:39:16,589 DEBUG PROTOCOL:simple BIND request <{'authentication': {'simple': '<password>', 'sasl': None}, 'version': 3, 'name': 'CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=my_company,DC=my_company,DC=org'}> sent via <ldaps://ldap-server - ssl - user: CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=my_company,DC=my_company,DC=org - unbound - open - <local: 10.128.32.247:57723 - remote: 10.129.1.242:636> - tls not started - listening - SyncStrategy>
2015-07-09 09:39:16,589 DEBUG PROTOCOL:new message id <3> generated
...
2015-07-09 09:39:16,592 DEBUG EXTENDED:ldap message sent via <ldaps://ldap-server - ssl - user: CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=my_company,DC=my_company,DC=org - unbound - open - <local: 10.128.32.247:57723 - remote: 10.129.1.242:636> - tls not started - listening - SyncStrategy>:
>>LDAPMessage:
>> messageID=3
>> protocolOp=ProtocolOp:
>>  bindRequest=BindRequest:
>>   version=3
>>   name=CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=my_company,DC=my_company,DC=org
>>   authentication=AuthenticationChoice:
>>    simple=<password>
2015-07-09 09:39:16,592 DEBUG NETWORK:sent 98 bytes via <ldaps://ldap-server - ssl - user: CN=Rodrigue Cloutier,OU=Users,OU=MTL,OU=my_company,DC=my_company,DC=org - unbound - open - <local: 10.128.32.247:57723 - remote: 10.129.1.242:636> - tls not started - listening - SyncStrategy>
```
Anything that might be needed on the plugin to make sure it uses the default?

**Comment by rodcloutier** [comment]
With ldap3 0.9.8.6 nothing related to ldap is outputted. I guess the password is not visible anymore!

**Comment by fschulze** [comment]
So your earlier comment was a false alarm? If so, I will update setup.py and make a release.

**Comment by rodcloutier** [comment]
Yep, false alarm. I had some issues with my virtualenv. All seems good. 

Sorry about that.

**Comment by fschulze** [comment]
Released 1.1.1 which requires the correct minimum ldap3 version.
